#!/bin/bash
usage()
{
cat << EOF
$(basename "$0"):
    Utility to help with LUTE. Different options provide messages on usage and
    parameters for various LUTE functionality.

    Options:
        -h|--help
          Display this message.

        Task Parameters
        ---------------
        -T|-t|--Task
          Display a table of parameter descriptions for the provided Task.
        --full_schema
          If passed, will provide the full schema of the Pydantic model.
          Otherwise, a formatted table of selected fields will be shown.
EOF
}

POS=()
while [[ $# -gt 0 ]]
do
    flag="$1"

    case $flag in
        -h|--help)
          usage
          exit
          ;;
        -T|-t|--Task)
          TASKNAME="$2"
          shift
          shift
          ;;
        --full_schema)
          FULL_SCHEMA=1
          shift
          ;;
    esac
done
set -- "${POS[@]}"

export APP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )/src/help"
export LUTE_BASE="${APP_DIR}/../../.."

export PYTHONPATH="${LUTE_BASE}:$PYTHONPATH"

if [[ $HOSTNAME =~ "sdf" ]]; then
    source /sdf/group/lcls/ds/ana/sw/conda1/manage/bin/psconda.sh
fi

if [[ $TASKNAME ]]; then
    CMD="python -B ${APP_DIR}/task_parameters.py --Task ${TASKNAME}"
    if [[ $FULL_SCHEMA ]]; then
        CMD="${CMD} --full_schema"
    fi
    $CMD
fi

if [[ $FULL_SCHEMA && -z $TASKNAME ]]; then
    echo "Full schema can only be used with -T <taskname>"
fi
